apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-app
  namespace: argocd
  metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-app=docker.io/rukevweubio/my-app
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:

  project: default
  source:
    repoURL: https://github.com/rukevweubio/01-Devops-Dockerswarm.git
    targetRevision: main
    path: apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
