apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-app
  namespace: velero # Adjust this if your app stays in a different namespace
  labels:
    app: bitcoin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitcoin-app
  template:
    metadata:
      labels:
        app: bitcoin-app
    spec:
      containers:
      - name: bitcoin-app
        image: rukevweubio/01-devops-dockerswarm:latest 
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
       