apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: minio-creds-sync
  namespace: velero
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-minio-backend 
    kind: SecretStore
  target:
    name: minio-creds-k8s
  data:
  - secretKey: rootUser
    remoteRef:
      key: creds
      property: rootUser
  - secretKey: rootPassword
    remoteRef:
      key: creds
      property: rootPassword