apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-creds-sync
  namespace: velero
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio-creds-k8s # This is the secret MinIO will eventually use
  data:
  - secretKey: rootUser
    remoteRef:
      key: creds # This is the name of your secret in Vault
      property: rootUser
  - secretKey: rootPassword
    remoteRef:
      key: creds # This is the name of your secret in Vault
      property: rootPassword