name: Build and Deploy to OpenShift

on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: bitcoin-app
  QUAY_USER: ubiowororuki
  OPENSHIFT_NAMESPACE: ubiowororuki-dev
  OPENSHIFT_DEPLOY_NAME: bitcoin-app

jobs:

  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint GitHub Actions workflow
        uses: reviewdog/action-actionlint@v1

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-workflow
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build App
        working-directory: bitcoin-app
        run: |
          npm ci
          npm run build

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push Docker Image to Quay.io
        run: |
          docker build -t "quay.io/${{ env.QUAY_USER }}/$IMAGE_NAME:latest" ./bitcoin-app
          docker push "quay.io/${{ env.QUAY_USER }}/$IMAGE_NAME:latest"

  deploy-openshift:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login "${{ secrets.OPENSHIFT_API }}" \
            --token="${{ secrets.OPENSHIFT_TOKEN }}" \
            --insecure-skip-tls-verify=true

      - name: Set OpenShift Project
        run: oc project ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Apply Deployment
        run: |
          cat <<EOF > deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${{ env.OPENSHIFT_DEPLOY_NAME }}
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: ${{ env.OPENSHIFT_DEPLOY_NAME }}
            template:
              metadata:
                labels:
                  app: ${{ env.OPENSHIFT_DEPLOY_NAME }}
              spec:
                containers:
                  - name: ${{ env.OPENSHIFT_DEPLOY_NAME }}
                    image: quay.io/${{ env.QUAY_USER }}/$IMAGE_NAME:latest
                    ports:
                      - containerPort: 8080
          EOF
          oc apply -f deployment.yaml

      - name: Apply Service
        run: |
          cat <<EOF > service.yaml
          apiVersion: v1
          kind: Service
          metadata:
            name: ${{ env.OPENSHIFT_DEPLOY_NAME }}
          spec:
            selector:
              app: ${{ env.OPENSHIFT_DEPLOY_NAME }}
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080
          EOF
          oc apply -f service.yaml