name: CI-CD Pipeline
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-minikube:
    runs-on: arc-runner-set 
    steps:
      - name: Hello from Pod
        run: |
          echo "I am running in a transient pod on Minikube!"
          uptime

  parallel-test:
    runs-on: arc-runner-set
    needs: [check-minikube]
    strategy:
      matrix:
        job_number: [1, 2, 3, 4, 5]
    steps:
      - name: Heavy Work Simulation
        run: |
          echo "Starting Job ${{ matrix.job_number }} on Minikube"
          sleep 10
          echo "Job ${{ matrix.job_number }} complete!"

  build:
    runs-on: arc-runner-set
    needs: [parallel-test] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./bitcoin-app
          push: true
          # Using github.sha ensures Argo CD sees a change in the manifest
          tags: |
            rukevweubio/01-devops-dockerswarm:latest
            rukevweubio/01-devops-dockerswarm:${{ github.sha }}

 