name: Test Minikube Runner
on: workflow_dispatch 

jobs:
  check-minikube:
    runs-on: arc-runner-set 
    steps:
      - name: Hello from Pod
        run: |
          echo "I am running in a transient pod on Minikube!"
          uptime

  parallel-test:
    runs-on: arc-runner-set
    needs: [check-minikube]
    strategy:
      matrix:
        job_number: [1, 2, 3, 4, 5]
    steps:
      - name: Heavy Work Simulation
        run: |
          echo "Starting Job ${{ matrix.job_number }} on Minikube"
          echo "I will sleep for 60 seconds to stay active..."
          sleep 60
          echo "Job ${{ matrix.job_number }} complete!"